[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
linker = "aarch64-linux-gnu-gcc"
